### ISSUE TITLE
Countandra architecture?

### ISSUE THREAD

**Issue by mihneagiurgea** [milindparikh/Countandra#1]
I just read about this project and it looks very promising :)

I'm curious about the details of how the counts are structured at the database level. Could you please write some more details on how that's done (like database schema)? Maybe even put it on the wiki or the main site, I'm sure a lot of people would be interested in how it's done. 

P.S.: Nice name choice ;)

**Comment by milindparikh** [comment]
http://www.countandra.org/?q=node/17
