### ISSUE TITLE
testing countrandra

### ISSUE THREAD

**Issue by victorsosa** [milindparikh/Countandra#2]
I did the countrandra's install  and I found that I can do the POST to insert the data but I can't get the data from the server using the GET using the firefox web browser.

http://localhost:8080/insert?c=pc&s=com.mywebsite.music&t=1350230221&v=200

http://localhost:8080/pc/com.mywebsite.music/LASTHOUR/MINUTELY

can you help me with this? I want to check countandra

**Comment by engleae** [comment]
Hello Victorosa,

I am having the same problem.  Have you been able to get this to work?  I get no data from the query, nor do I see data in Cassandra.  Any hints you may have would be appreciated.

One thing you should try: when you query for data, be sure to put "query" just after your localhost hostname, like so:
http://localhost:8080/query/pc/com.mywebsite.music/LASTHOUR/MINUTELY

That may actually return some data for you if everything is running correctly.

Thanks,
Andy

**Comment by victorsosa** [comment]
Yep you are right, the get is working even if the data is empty; for the insert you need to use NETTY api that's the only way it is working for me (forget about the firefox try you can do it, only for query no for insert ); checkout the example in the countandra code.

**Comment by milindparikh** [comment]
We are using the HTTP protocol for it's intended use. 
HTTP POST writes the data.
HTTP GET returns the results.

**Comment by engleae** [comment]
I am using cURL to post data to Countandra and it seems to work fine.  Problem is, we have no data written to Cassandra.  I'm not sure if it's a problem with the configuration, or if the code simply doesn't work.  Have you verified data is written to your Cassandra instance?

**Comment by engleae** [comment]
One other thing -- the DDCC keyspace is present in Cassandra, so it seems like Countandra is connecting.  However, there is never any data written.  I am using some example data from the tinyfile.txt file.  Also, we are posting data from a PHP form, in addition to trying the posting using cURL.  There seems to be no sign of errors, it's just not working.

**Comment by victorsosa** [comment]
yes mine is writing data into Casandra. I am using the Netty api to send the data; I stopped use pure HTTP client because it wasn't working. And yes the error log is not GOOD enough.

Please check this code NeetyUtils.messageReceived() so you can understand how it manage the messages.
Countandra is using Netty, so in order to get a successfull insert I am sending the packages using Netty too.

you can find a client side code  here:
/Countandra/src/org/countandra/unittests/CountandraTestCases.java 

I found a weird behavior of the Netty api; well It wasn't working fast enough in the writing, so I have to reduce the batch process implemented from 2000 to 100 (my system need a lot more writings that readings), but still not enough so I am researching Casandra and Netty doc about it.

sorry for the delay; Live is a little complicated.

**Comment by nehalmehta** [comment]
If you are using via CURL probably request.getUri would receive /insert instead of insert  and so it does not take action. 

When you run it via CURL try to debug request.getUri on line 146 for NettyUtils.   I will fix it over weekend so that it can receive via CURL as well as Netty Client

**Comment by nehalmehta** [comment]
Command curl --data "c=pti&s=com.amazon.music&t=1320552120000&v=200" http://localhost:8080/insert should be working for you now.
